name: Build app

on: [ push, pull_request ]

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
      CONAN_REVISIONS_ENABLED: 1
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v3

      - name: Install Build tools
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{BUILD_TOOLS_PATH})
          file(DOWNLOAD https://cdn.anotherfoxguy.com/build-tools.zip "$ENV{TMP}/build-tools.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/build-tools.zip" WORKING_DIRECTORY "$ENV{BUILD_TOOLS_PATH}")

      - name: Cache conan packages Part 1
        uses: actions/cache@v3
        with:
          key: conan-user-${{ hashFiles('cmake/DependenciesConfig.cmake') }}
          path: ~/.conan
      - name: Cache conan packages Part 2
        uses: actions/cache@v3
        with:
          key: conan-root-${{ hashFiles('cmake/DependenciesConfig.cmake') }}
          path: C:/.conan/

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Configure
        run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=redist .
        shell: cmd

      - name: Build
        run: ninja install
        shell: cmd

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: meshy-win
          path: redist

      - name: Clean Conan pkgs
        run: conan remove "*" -fsb
        shell: cmd
